Initial version - review PR
3mdeb/MbedTLS_services pull request #1
Opened 2024-08-09 12:15 UTC by tym2k1

`psa_util.cpp` is not used in demo scenario but left for now.

2024-08-09 14:41 UTC, DaniilKl requested changes
Some typos

2024-08-09 14:41 UTC, DaniilKl commented on README.md
> +by OpenSSL beforehand
```suggestion
The demo currently doesn't utilize MbedTLS/PSA Crypto API and certificates are
 generated by OpenSSL beforehand.
```

2024-08-09 14:41 UTC, DaniilKl commented on README.md
> +If you have `nix` installed you can easily enter a shell with dependancies with:
```suggestion
If you have `nix` installed you can easily enter a shell with dependencies with:
```

2024-08-09 14:41 UTC, DaniilKl commented on README.md
> +It's recommended to store all certificates in the `keys` directory of repo
```suggestion
It's recommended to store all certificates in the `keys` directory of repo:
```

2024-08-09 14:41 UTC, DaniilKl commented on README.md
> +which we'll use in testing scenarios
```suggestion
which we'll use in testing scenarios.
```

2024-08-09 14:41 UTC, DaniilKl commented on README.md
> +
```suggestion

```

2024-08-09 14:41 UTC, DaniilKl commented on README.md
> +Certificate Configuration (cert.conf)
```suggestion
Certificate Configuration (cert.conf).
```

2024-08-09 15:30 UTC, tym2k1 commented on README.md
> +by OpenSSL beforehand
[Adresssed](https://github.com/3mdeb/MbedTLS_services/pull/1/commits/402278412049648ec96d9dd5d496085eb6f7b6a0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R8)

2024-08-09 15:30 UTC, tym2k1 commented on README.md
> +If you have `nix` installed you can easily enter a shell with dependancies with:
[Adressed](https://github.com/3mdeb/MbedTLS_services/pull/1/commits/402278412049648ec96d9dd5d496085eb6f7b6a0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R39)

2024-08-09 15:30 UTC, tym2k1 commented on README.md
> +which we'll use in testing scenarios
[Adressed](https://github.com/3mdeb/MbedTLS_services/pull/1/commits/402278412049648ec96d9dd5d496085eb6f7b6a0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R71)

2024-08-09 15:31 UTC, tym2k1 commented on README.md
> +It's recommended to store all certificates in the `keys` directory of repo
[Adressed](https://github.com/3mdeb/MbedTLS_services/pull/1/commits/402278412049648ec96d9dd5d496085eb6f7b6a0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R84)

2024-08-09 15:31 UTC, tym2k1 commented on README.md
> +
[Adressed](https://github.com/3mdeb/MbedTLS_services/pull/1/commits/402278412049648ec96d9dd5d496085eb6f7b6a0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L77)

2024-08-09 15:31 UTC, tym2k1 commented on README.md
> +Certificate Configuration (cert.conf)
[Adressed](https://github.com/3mdeb/MbedTLS_services/pull/1/commits/402278412049648ec96d9dd5d496085eb6f7b6a0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R132)

2024-08-09 15:32 UTC, tym2k1 commented
Review adressed

2024-08-12 08:29 UTC, DaniilKl requested changes

2024-08-12 08:29 UTC, DaniilKl commented on README.md
> +#### Correct server certificate incorrect client certificate - access refused
```suggestion
#### Correct server certificate and incorrect client certificate - access refused
```

2024-08-12 08:29 UTC, DaniilKl commented on README.md
> +#### Incorrect server certificate - client doesn't try to connect
```suggestion
#### Incorrect server certificate - client doesn't connect
```

It tries, but fails.

Consider adding explanation to this part, it is not very self-explanatory.

2024-08-12 08:29 UTC, DaniilKl commented on README.md
> +#### `mbedtls_script_server`
```suggestion
##### `mbedtls_script_server`
```

2024-08-12 10:35 UTC, tym2k1 commented on README.md
> +#### Incorrect server certificate - client doesn't try to connect
It verifies that the certificate is not trusted and stops the handshake. It's explained at the [# Client Verifying the Server's Authenticity](https://github.com/3mdeb/MbedTLS_services/tree/review?tab=readme-ov-file#client-verifying-the-servers-authenticity)

2024-08-12 11:49 UTC, tym2k1 commented on README.md
> +#### Correct server certificate incorrect client certificate - access refused
Adressed

2024-08-12 11:49 UTC, tym2k1 commented on README.md
> +#### `mbedtls_script_server`
[Adressed](https://github.com/3mdeb/MbedTLS_services/pull/1/commits/3c1c4b982826f3947572d469c38f374cc4dd5a68#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R242) and changed the following headers to match it

2024-08-12 12:00 UTC, merged